/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as MfiRouteImport } from './routes/mfi'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as MfiIndexRouteImport } from './routes/mfi.index'
import { Route as PortalReadinessRouteImport } from './routes/portal.readiness'
import { Route as PortalProfileRouteImport } from './routes/portal.profile'
import { Route as MfiClientsRouteImport } from './routes/mfi.clients'
import { Route as MfiAnalyticsRouteImport } from './routes/mfi.analytics'
import { Route as AuthRegisterLearnerRouteImport } from './routes/auth.register-learner'
import { Route as AuthRegisterRouteImport } from './routes/auth.register'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as PortalQuizQuizIdRouteImport } from './routes/portal.quiz.$quizId'
import { Route as PortalModulesModuleIdRouteImport } from './routes/portal.modules.$moduleId'

const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const MfiRoute = MfiRouteImport.update({
  id: '/mfi',
  path: '/mfi',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const MfiIndexRoute = MfiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MfiRoute,
} as any)
const PortalReadinessRoute = PortalReadinessRouteImport.update({
  id: '/readiness',
  path: '/readiness',
  getParentRoute: () => PortalRoute,
} as any)
const PortalProfileRoute = PortalProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PortalRoute,
} as any)
const MfiClientsRoute = MfiClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => MfiRoute,
} as any)
const MfiAnalyticsRoute = MfiAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => MfiRoute,
} as any)
const AuthRegisterLearnerRoute = AuthRegisterLearnerRouteImport.update({
  id: '/auth/register-learner',
  path: '/auth/register-learner',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalQuizQuizIdRoute = PortalQuizQuizIdRouteImport.update({
  id: '/quiz/$quizId',
  path: '/quiz/$quizId',
  getParentRoute: () => PortalRoute,
} as any)
const PortalModulesModuleIdRoute = PortalModulesModuleIdRouteImport.update({
  id: '/modules/$moduleId',
  path: '/modules/$moduleId',
  getParentRoute: () => PortalRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mfi': typeof MfiRouteWithChildren
  '/portal': typeof PortalRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/register-learner': typeof AuthRegisterLearnerRoute
  '/mfi/analytics': typeof MfiAnalyticsRoute
  '/mfi/clients': typeof MfiClientsRoute
  '/portal/profile': typeof PortalProfileRoute
  '/portal/readiness': typeof PortalReadinessRoute
  '/mfi/': typeof MfiIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/portal/modules/$moduleId': typeof PortalModulesModuleIdRoute
  '/portal/quiz/$quizId': typeof PortalQuizQuizIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/register-learner': typeof AuthRegisterLearnerRoute
  '/mfi/analytics': typeof MfiAnalyticsRoute
  '/mfi/clients': typeof MfiClientsRoute
  '/portal/profile': typeof PortalProfileRoute
  '/portal/readiness': typeof PortalReadinessRoute
  '/mfi': typeof MfiIndexRoute
  '/portal': typeof PortalIndexRoute
  '/portal/modules/$moduleId': typeof PortalModulesModuleIdRoute
  '/portal/quiz/$quizId': typeof PortalQuizQuizIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mfi': typeof MfiRouteWithChildren
  '/portal': typeof PortalRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/register-learner': typeof AuthRegisterLearnerRoute
  '/mfi/analytics': typeof MfiAnalyticsRoute
  '/mfi/clients': typeof MfiClientsRoute
  '/portal/profile': typeof PortalProfileRoute
  '/portal/readiness': typeof PortalReadinessRoute
  '/mfi/': typeof MfiIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/portal/modules/$moduleId': typeof PortalModulesModuleIdRoute
  '/portal/quiz/$quizId': typeof PortalQuizQuizIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/mfi'
    | '/portal'
    | '/auth/login'
    | '/auth/register'
    | '/auth/register-learner'
    | '/mfi/analytics'
    | '/mfi/clients'
    | '/portal/profile'
    | '/portal/readiness'
    | '/mfi/'
    | '/portal/'
    | '/portal/modules/$moduleId'
    | '/portal/quiz/$quizId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/login'
    | '/auth/register'
    | '/auth/register-learner'
    | '/mfi/analytics'
    | '/mfi/clients'
    | '/portal/profile'
    | '/portal/readiness'
    | '/mfi'
    | '/portal'
    | '/portal/modules/$moduleId'
    | '/portal/quiz/$quizId'
  id:
    | '__root__'
    | '/'
    | '/mfi'
    | '/portal'
    | '/auth/login'
    | '/auth/register'
    | '/auth/register-learner'
    | '/mfi/analytics'
    | '/mfi/clients'
    | '/portal/profile'
    | '/portal/readiness'
    | '/mfi/'
    | '/portal/'
    | '/portal/modules/$moduleId'
    | '/portal/quiz/$quizId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MfiRoute: typeof MfiRouteWithChildren
  PortalRoute: typeof PortalRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthRegisterLearnerRoute: typeof AuthRegisterLearnerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mfi': {
      id: '/mfi'
      path: '/mfi'
      fullPath: '/mfi'
      preLoaderRoute: typeof MfiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/mfi/': {
      id: '/mfi/'
      path: '/'
      fullPath: '/mfi/'
      preLoaderRoute: typeof MfiIndexRouteImport
      parentRoute: typeof MfiRoute
    }
    '/portal/readiness': {
      id: '/portal/readiness'
      path: '/readiness'
      fullPath: '/portal/readiness'
      preLoaderRoute: typeof PortalReadinessRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/profile': {
      id: '/portal/profile'
      path: '/profile'
      fullPath: '/portal/profile'
      preLoaderRoute: typeof PortalProfileRouteImport
      parentRoute: typeof PortalRoute
    }
    '/mfi/clients': {
      id: '/mfi/clients'
      path: '/clients'
      fullPath: '/mfi/clients'
      preLoaderRoute: typeof MfiClientsRouteImport
      parentRoute: typeof MfiRoute
    }
    '/mfi/analytics': {
      id: '/mfi/analytics'
      path: '/analytics'
      fullPath: '/mfi/analytics'
      preLoaderRoute: typeof MfiAnalyticsRouteImport
      parentRoute: typeof MfiRoute
    }
    '/auth/register-learner': {
      id: '/auth/register-learner'
      path: '/auth/register-learner'
      fullPath: '/auth/register-learner'
      preLoaderRoute: typeof AuthRegisterLearnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/quiz/$quizId': {
      id: '/portal/quiz/$quizId'
      path: '/quiz/$quizId'
      fullPath: '/portal/quiz/$quizId'
      preLoaderRoute: typeof PortalQuizQuizIdRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/modules/$moduleId': {
      id: '/portal/modules/$moduleId'
      path: '/modules/$moduleId'
      fullPath: '/portal/modules/$moduleId'
      preLoaderRoute: typeof PortalModulesModuleIdRouteImport
      parentRoute: typeof PortalRoute
    }
  }
}

interface MfiRouteChildren {
  MfiAnalyticsRoute: typeof MfiAnalyticsRoute
  MfiClientsRoute: typeof MfiClientsRoute
  MfiIndexRoute: typeof MfiIndexRoute
}

const MfiRouteChildren: MfiRouteChildren = {
  MfiAnalyticsRoute: MfiAnalyticsRoute,
  MfiClientsRoute: MfiClientsRoute,
  MfiIndexRoute: MfiIndexRoute,
}

const MfiRouteWithChildren = MfiRoute._addFileChildren(MfiRouteChildren)

interface PortalRouteChildren {
  PortalProfileRoute: typeof PortalProfileRoute
  PortalReadinessRoute: typeof PortalReadinessRoute
  PortalIndexRoute: typeof PortalIndexRoute
  PortalModulesModuleIdRoute: typeof PortalModulesModuleIdRoute
  PortalQuizQuizIdRoute: typeof PortalQuizQuizIdRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalProfileRoute: PortalProfileRoute,
  PortalReadinessRoute: PortalReadinessRoute,
  PortalIndexRoute: PortalIndexRoute,
  PortalModulesModuleIdRoute: PortalModulesModuleIdRoute,
  PortalQuizQuizIdRoute: PortalQuizQuizIdRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MfiRoute: MfiRouteWithChildren,
  PortalRoute: PortalRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthRegisterLearnerRoute: AuthRegisterLearnerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
